### ISSUE TITLE
Transaction GET request failing

### ISSUE THREAD

**Issue by overweightdev** [plaid/plaid-java#362] opened 2022-10-11 00:51 UTC
Making a transactionsGet request with count and offset parameters in the TransactionsGetRequestOptions fails with a BadRequest error.

The bug has been confirmed by Plaid support.

Plaid version 12.0.0

**Comment by phoenixy1** [comment] 2022-10-12 21:29
@overweightdev Sorry for the miscommunication -- after further investigation we were not able to reproduce this issue. I see you have a ticket open with support so I'll suggest you continue any debugging on that thread and I'll be closing this ticket as we weren't able to identify a problem with the Java SDK. If it helps at all, here's the code I used that worked successfully with version 12.0.0 of the Plaid Java SDK:

```
  public TransactionsGetResponse getTransactions() throws IOException {
    LocalDate startDate = LocalDate.now().minusDays(30);
    LocalDate endDate = LocalDate.now();

    TransactionsGetRequestOptions options = new TransactionsGetRequestOptions()
    .count(100)
    .offset(5);

    TransactionsGetRequest request = new TransactionsGetRequest()
      .accessToken(accessToken)
      .startDate(startDate)
      .endDate(endDate)
      .options(options);

    Response<TransactionsGetResponse> response = null;
    response = plaidClient.transactionsGet(request).execute(); 
```

**Closed by phoenixy1** 2022-10-12 21:29 UTC
